name: lmwannettajohnson-hamrell.com
favicon: null
layout_spectrum: 0.19265320408158004
typography_spectrum: 0.6120433530304581
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9544243346899748
  lightness: 0.39697385230101645
  saturation: 0.6795788465533406
  rhythmicContrast: 0.6739110094495118
purpose: []
